export const INITIAL_STATE = {
  recipes: [],
  persistRecipeIsLoading: false,
  persistRecipeErrorMessage: null,
  recipeIsExternal: false,
  fetchRecipesIsLoading: false,
  remoteRecipes: [],
  fetchRemoteRecipesIsLoading: false,
  fetchRemoteRecipesErrorMessage: null,
  deleteRecipeIsLoading: false,
  sharedRecipe: null,
  fetchSharedRecipeIsLoading: false,
  shareLink: null,
  createSharedRecipeIsLoading: false,
  createSharedRecipeErrorMessage: null,
}
