/**
 * Images should be stored in the `App/Images` directory and referenced using variables defined here.
 */

export default {
  logo: require('../Assets/Images/mixxy_logo.png'),
  builderUp: require('../Assets/Images/buttons/Builder_Up.png'),
  builderDown: require('../Assets/Images/buttons/Builder_Down.png'),
  builderDelete: require('../Assets/Images/buttons/Builder_Delete.png'),
  navDiscoverLight: require('../Assets/Images/tabs/NavMenu_Discover_LIGHT.png'),
  navDiscoverDark: require('../Assets/Images/tabs/NavMenu_Discover_DARK.png'),
  navDiscoverSelected: require('../Assets/Images/tabs/NavMenu_Discover_ACTIVE.png'),
  navLibraryLight: require('../Assets/Images/tabs/NavMenu_Library_LIGHT.png'),
  navLibraryDark: require('../Assets/Images/tabs/NavMenu_Library_DARK.png'),
  navLibrarySelected: require('../Assets/Images/tabs/NavMenu_Library_ACTIVE.png'),
  navSettingsLight: require('../Assets/Images/tabs/NavMenu_User_LIGHT.png'),
  navSettingsDark: require('../Assets/Images/tabs/NavMenu_User_DARK.png'),
  navSettingsSelected: require('../Assets/Images/tabs/NavMenu_User_ACTIVE.png'),
  xCampaign: require('../Assets/Images/buttons/X_Campaign.png'),
  proBadge: require('../Assets/Images/Asset_11.png'),
  newRecipe: require('../Assets/Images/buttons/NewRecipe_Plus.png'),
  quantityPlus: require('../Assets/Images/buttons/Qty_Plus.png'),
  quantityPlusInactiveLight: require('../Assets/Images/buttons/Qty_Plus_Inactive_LIGHT.png'),
  quantityPlusInactiveDark: require('../Assets/Images/buttons/Qty_Plus_Inactive_DARK.png'),
  quantityMinus: require('../Assets/Images/buttons/Qty_Minus.png'),
  quantityMinusInactiveLight: require('../Assets/Images/buttons/Qty_Minus_Inactive_LIGHT.png'),
  quantityMinusInactiveDark: require('../Assets/Images/buttons/Qty_Minus_Inactive_DARK.png'),
  ingredientX: require('../Assets/Images/buttons/Ingredient_X.png'),
  topHeaderXLight: require('../Assets/Images/buttons/TopBar_X_DARK.png'),
  topHeaderXDark: require('../Assets/Images/buttons/TopBar_X_LIGHT.png'),
  topHeaderBackLight: require('../Assets/Images/buttons/TopBar_Back_DARK.png'),
  topHeaderBackDark: require('../Assets/Images/buttons/TopBar_Back_LIGHT.png'),
  favoriteEmpty: require('../Assets/Images/buttons/Favorite_Empty.png'),
  favoriteFull: require('../Assets/Images/buttons/Favorite_Full.png'),
  glassFlute: require('../Assets/Images/glasses/Glass_Flute.png'),
  glassMarg: require('../Assets/Images/glasses/Glass_Marg.png'),
  glassMartini: require('../Assets/Images/glasses/Glass_Martini.png'),
  glassPitcher: require('../Assets/Images/glasses/Glass_Pitcher.png'),
  glassShort: require('../Assets/Images/glasses/Glass_Short.png'),
  glassShot: require('../Assets/Images/glasses/Glass_Shot.png'),
  glassTall: require('../Assets/Images/glasses/Glass_Tall.png'),
  arrowDark: require('../Assets/Images/buttons/Arrow_Small_DARK.png'),
  arrowLight: require('../Assets/Images/buttons/Arrow_Small_LIGHT.png'),
}
