/**
 * Images should be stored in the `App/Images` directory and referenced using variables defined here.
 */

export default {
  logo: require('../Assets/Images/mixxy_logo.png'),
  // Home tabs
  navDiscoverLight: require('../Assets/Images/tabs/NavMenu_Discover_LIGHT.png'),
  navDiscoverDark: require('../Assets/Images/tabs/NavMenu_Discover_DARK.png'),
  navDiscoverSelected: require('../Assets/Images/tabs/NavMenu_Discover_ACTIVE.png'),
  navLibraryLight: require('../Assets/Images/tabs/NavMenu_Library_LIGHT.png'),
  navLibraryDark: require('../Assets/Images/tabs/NavMenu_Library_DARK.png'),
  navLibrarySelected: require('../Assets/Images/tabs/NavMenu_Library_ACTIVE.png'),
  navSettingsLight: require('../Assets/Images/tabs/NavMenu_User_LIGHT.png'),
  navSettingsDark: require('../Assets/Images/tabs/NavMenu_User_DARK.png'),
  navSettingsSelected: require('../Assets/Images/tabs/NavMenu_User_ACTIVE.png'),
  navBartenderLight: require('../Assets/Images/tabs/NavMenu_Bartender_LIGHT.png'),
  navBartenderDark: require('../Assets/Images/tabs/NavMenu_Bartender_DARK.png'),
  navBartenderSelected: require('../Assets/Images/tabs/NavMenu_Bartender_ACTIVE.png'),
  xCampaign: require('../Assets/Images/buttons/X_Campaign.png'),
  proBadge: require('../Assets/Images/Asset_11.png'),
  newRecipe: require('../Assets/Images/buttons/NewRecipe_Plus.png'),
  quantityPlus: require('../Assets/Images/buttons/Qty_Plus.png'),
  quantityPlusInactiveLight: require('../Assets/Images/buttons/Qty_Plus_Inactive_LIGHT.png'),
  quantityPlusInactiveDark: require('../Assets/Images/buttons/Qty_Plus_Inactive_DARK.png'),
  quantityMinus: require('../Assets/Images/buttons/Qty_Minus.png'),
  quantityMinusInactiveLight: require('../Assets/Images/buttons/Qty_Minus_Inactive_LIGHT.png'),
  quantityMinusInactiveDark: require('../Assets/Images/buttons/Qty_Minus_Inactive_DARK.png'),
  ingredientX: require('../Assets/Images/buttons/Ingredient_X.png'),
  arrowDark: require('../Assets/Images/buttons/Arrow_Small_DARK.png'),
  arrowLight: require('../Assets/Images/buttons/Arrow_Small_LIGHT.png'),
  spotlightLocation: require('../Assets/Images/Spotlight_Location.png'),
  spotlightType: require('../Assets/Images/Spotlight_Type.png'),
  introArrow: require('../Assets/Images/buttons/Intro_Arrow.png'),
  barCartIcon: require('../Assets/Images/barcart.png'),
  checkmarkBox: require('../Assets/Images/buttons/checkmark_box.png'),
  // Drink type art
  glassFlute: require('../Assets/Images/glasses/Glass_Flute.png'),
  glassMarg: require('../Assets/Images/glasses/Glass_Margarita.png'),
  glassMartini: require('../Assets/Images/glasses/Glass_Martini.png'),
  glassPitcher: require('../Assets/Images/glasses/Glass_Pitcher.png'),
  glassShort: require('../Assets/Images/glasses/Glass_Rocks.png'),
  glassShot: require('../Assets/Images/glasses/Glass_Shot.png'),
  glassTall: require('../Assets/Images/glasses/Glass_Highball.png'),
  glassPint: require('../Assets/Images/glasses/Glass_Pint.png'),
  glassWine: require('../Assets/Images/glasses/Glass_Wine.png'),
  glassCoupe: require('../Assets/Images/glasses/Glass_Coupe.png'),
  glassCopperMug: require('../Assets/Images/glasses/Glass_CopperMug.png'),
  iconFlute: require('../Assets/Images/glasses/Icon_Flute.png'),
  iconMarg: require('../Assets/Images/glasses/Icon_Margarita.png'),
  iconMartini: require('../Assets/Images/glasses/Icon_Martini.png'),
  iconPitcher: require('../Assets/Images/glasses/Icon_Pitcher.png'),
  iconShort: require('../Assets/Images/glasses/Icon_Rocks.png'),
  iconShot: require('../Assets/Images/glasses/Icon_Shot.png'),
  iconTall: require('../Assets/Images/glasses/Icon_Highball.png'),
  iconPint: require('../Assets/Images/glasses/Icon_Pint.png'),
  iconWine: require('../Assets/Images/glasses/Icon_Wine.png'),
  iconCoupe: require('../Assets/Images/glasses/Icon_Coupe.png'),
  iconCopperMug: require('../Assets/Images/glasses/Icon_CopperMug.png'),
  // Modals
  modalEditDark: require('../Assets/Images/modal/Modal_Edit_DARK.png'),
  modalEditLight: require('../Assets/Images/modal/Modal_Edit_LIGHT.png'),
  modalViewDark: require('../Assets/Images/modal/Modal_View_DARK.png'),
  modalViewLight: require('../Assets/Images/modal/Modal_View_LIGHT.png'),
  modalTrash: require('../Assets/Images/modal/Modal_Trash.png'),
  modalNo: require('../Assets/Images/modal/Modal_No.png'),
  modalShareDark: require('../Assets/Images/modal/Modal_Share_DARK.png'),
  modalShareLight: require('../Assets/Images/modal/Modal_Share_LIGHT.png'),
  modalFavoriteDark: require('../Assets/Images/modal/Modal_Favorite_DARK.png'),
  modalFavoriteLight: require('../Assets/Images/modal/Modal_Favorite_LIGHT.png'),
  modalUnfavoriteDark: require('../Assets/Images/modal/Modal_Unfavorite_DARK.png'),
  modalUnfavoriteLight: require('../Assets/Images/modal/Modal_Unfavorite_LIGHT.png'),
  proModalBadge: require('../Assets/Images/modal/Badge_MixxyPro.png'),
  notificationsBadge: require('../Assets/Images/modal/Badge_Notifications.png'),
  // Builder
  builderAddNew: require('../Assets/Images/new_builder/Builder_NewStep.png'),
  builderDeleteIngredient: require('../Assets/Images/new_builder/Builder_DeleteIngredient.png'),
  builderMoreDetails: require('../Assets/Images/new_builder/Builder_ThreeDots.png'),
  builderUnitArrowDark: require('../Assets/Images/new_builder/Builder_UnitArrow_DARK.png'),
  builderUnitArrowLight: require('../Assets/Images/new_builder/Builder_UnitArrow_LIGHT.png'),
  builderDeleteStep: require('../Assets/Images/new_builder/Builder_DeleteStep.png'),
  // Top header
  topHeaderShareDark: require('../Assets/Images/navbar/Nav_Share_DARK.png'),
  topHeaderShareLight: require('../Assets/Images/navbar/Nav_Share_LIGHT.png'),
  topHeaderFavoriteLight: require('../Assets/Images/navbar/Nav_Favorite_LIGHT.png'),
  topHeaderFavoriteDark: require('../Assets/Images/navbar/Nav_Favorite_DARK.png'),
  topHeaderUnfavoriteLight: require('../Assets/Images/navbar/Nav_Unavorite_LIGHT.png'),
  topHeaderUnfavoriteDark: require('../Assets/Images/navbar/Nav_Unfavorite_DARK.png'),
  topHeaderXLight: require('../Assets/Images/navbar/Nav_X_LIGHT.png'),
  topHeaderXDark: require('../Assets/Images/navbar/Nav_X_DARK.png'),
  topHeaderBackLight: require('../Assets/Images/navbar/Nav_Back_LIGHT.png'),
  topHeaderBackDark: require('../Assets/Images/navbar/Nav_Back_DARK.png'),
  topHeaderDotsLight: require('../Assets/Images/navbar/Nav_Dots_LIGHT.png'),
  topHeaderDotsDark: require('../Assets/Images/navbar/Nav_Dots_DARK.png'),
}
